import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import { Pool, PoolClient } from 'pg'; import xss from 'xss'; import { z } from 'zod'; import path from 'node:path';
const app=express(), pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('render.com')?{rejectUnauthorized:false}:undefined}), ttl=Number(process.env.LOCK_TTL_SECONDS||90);
app.use(helmet({contentSecurityPolicy:false})); app.use(cors({origin:process.env.CLIENT_ORIGIN?process.env.CLIENT_ORIGIN.split(','):false})); app.use(express.json({limit:'1mb'})); app.use('/api',rateLimit({windowMs:60_000,limit:180,standardHeaders:true,legacyHeaders:false}));
const who=z.object({userId:z.string().uuid(),firstName:z.string().trim().min(1).max(80),lastName:z.string().trim().min(1).max(80)});
function user(req:any){return who.parse({userId:req.header('x-user-id'),firstName:req.header('x-first-name'),lastName:req.header('x-last-name')})}
async function ensureUser(c:PoolClient,u:z.infer<typeof who>){await c.query('INSERT INTO users(id,first_name,last_name) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET first_name=EXCLUDED.first_name,last_name=EXCLUDED.last_name,updated_at=now()',[u.userId,u.firstName,u.lastName]);}
async function event(c:PoolClient,id:string,u:z.infer<typeof who>,type:string,target:string,details:any={}){await c.query('INSERT INTO history(table_id,user_id,first_name,last_name,event_type,target,details) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,u.userId,u.firstName,u.lastName,type,target,details]); await c.query('UPDATE tables SET version=version+1,updated_at=now() WHERE id=$1',[id]);}
async function editable(c:PoolClient,id:string,u:z.infer<typeof who>){const r=await c.query('SELECT l.user_id,l.last_heartbeat,u.first_name,u.last_name,l.started_at FROM edit_locks l JOIN users u ON u.id=l.user_id WHERE l.table_id=$1',[id]); if(!r.rowCount)return; const l=r.rows[0]; if(Date.now()-new Date(l.last_heartbeat).getTime()>ttl*1000){await c.query('DELETE FROM edit_locks WHERE table_id=$1',[id]);return;} if(l.user_id!==u.userId)throw Object.assign(new Error(`Alguém já está mexendo aí! ${l.first_name} ${l.last_name} está editando.`),{status:423});}
async function tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await pool.connect();try{await c.query('BEGIN');const x=await fn(c);await c.query('COMMIT');return x}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
app.get('/api/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:'postgresql'})}catch{res.status(503).json({ok:false,error:'PostgreSQL indisponível'})}});
app.get('/api/tables',async(req,res,next)=>{try{const archived=req.query.archived==='true';const r=await pool.query('SELECT t.*,u.first_name AS owner_first_name,u.last_name AS owner_last_name FROM tables t JOIN users u ON u.id=t.owner_user_id WHERE (t.archived_at IS NOT NULL)=$1 ORDER BY t.updated_at DESC',[archived]);res.json(r.rows)}catch(e){next(e)}});
app.post('/api/tables',async(req,res,next)=>{try{const u=user(req), b=z.object({name:z.string().trim().min(1).max(120),description:z.string().max(2000).default('')}).parse(req.body);const t=await tx(async c=>{await ensureUser(c,u);const r=await c.query('INSERT INTO tables(name,description,owner_user_id) VALUES($1,$2,$3) RETURNING *',[b.name,b.description,u.userId]);const id=r.rows[0].id;const cols=await c.query("INSERT INTO table_columns(table_id,position,label) VALUES($1,0,'Conceito'),($1,1,'Karl Marx'),($1,2,'Émile Durkheim'),($1,3,'Talcott Parsons') RETURNING id",[id]);for(let i=0;i<4;i++){const row=await c.query('INSERT INTO table_rows(table_id,position) VALUES($1,$2) RETURNING id',[id,i]);for(const col of cols.rows)await c.query('INSERT INTO cells(table_id,row_id,column_id) VALUES($1,$2,$3)',[id,row.rows[0].id,col.id]);}await event(c,id,u,'table_created','tabela',{name:b.name});return r.rows[0]});res.status(201).json(t)}catch(e){next(e)}});
app.get('/api/tables/:id',async(req,res,next)=>{try{const {id}=req.params;const t=await pool.query('SELECT * FROM tables WHERE id=$1',[id]);if(!t.rowCount)return res.status(404).json({error:'Tabela não encontrada'});const [rows,cols,cells,lock]=await Promise.all([pool.query('SELECT * FROM table_rows WHERE table_id=$1 ORDER BY position',[id]),pool.query('SELECT * FROM table_columns WHERE table_id=$1 ORDER BY position',[id]),pool.query('SELECT * FROM cells WHERE table_id=$1',[id]),pool.query('SELECT l.*,u.first_name,u.last_name FROM edit_locks l JOIN users u ON u.id=l.user_id WHERE l.table_id=$1 AND l.last_heartbeat>now()-($2||\' seconds\')::interval',[id,ttl])]);res.json({...t.rows[0],rows:rows.rows,columns:cols.rows,cells:cells.rows,lock:lock.rows[0]||null})}catch(e){next(e)}});
app.post('/api/tables/:id/lock',async(req,res,next)=>{try{const u=user(req),{id}=req.params;await tx(async c=>{await ensureUser(c,u);await c.query('DELETE FROM edit_locks WHERE table_id=$1 AND last_heartbeat<now()-($2||\' seconds\')::interval',[id,ttl]);const r=await c.query('INSERT INTO edit_locks(table_id,user_id) VALUES($1,$2) ON CONFLICT(table_id) DO UPDATE SET last_heartbeat=now() WHERE edit_locks.user_id=EXCLUDED.user_id RETURNING *',[id,u.userId]);if(!r.rowCount)throw Object.assign(new Error('Alguém já está mexendo aí!'),{status:423});await event(c,id,u,'edit_lock','tabela',{action:'adquirido'});});res.json({ok:true,ttl})}catch(e){next(e)}});
app.put('/api/tables/:id/lock',async(req,res,next)=>{try{const u=user(req);const r=await pool.query('UPDATE edit_locks SET last_heartbeat=now() WHERE table_id=$1 AND user_id=$2 RETURNING *',[req.params.id,u.userId]);if(!r.rowCount)return res.status(423).json({error:'Lock perdido'});res.json({ok:true})}catch(e){next(e)}});
app.delete('/api/tables/:id/lock',async(req,res,next)=>{try{const u=user(req);await pool.query('DELETE FROM edit_locks WHERE table_id=$1 AND user_id=$2',[req.params.id,u.userId]);res.json({ok:true})}catch(e){next(e)}});
app.put('/api/tables/:id/cells/:cellId',async(req,res,next)=>{try{const u=user(req),b=z.object({content:z.string().max(20000),style:z.record(z.string(),z.any()).optional()}).parse(req.body);await tx(async c=>{await editable(c,req.params.id,u);await ensureUser(c,u);const content=xss(b.content,{whiteList:{b:[],strong:[],i:[],em:[],u:[],s:[],strike:[],br:[],p:[],ul:[],ol:[],li:[],span:['style'],a:['href','target','rel']},onTagAttr:(_tag,attr,value)=>attr==='style'&&/^(color|background-color|font-size|font-family|text-align):[a-zA-Z0-9#(), .%\-]+$/.test(value)?`${attr}="${value}"`:''});const r=await c.query('UPDATE cells SET content=$1,style=COALESCE($2,style),updated_at=now() WHERE table_id=$3 AND id=$4 RETURNING *',[content,b.style?JSON.stringify(b.style):null,req.params.id,req.params.cellId]);if(!r.rowCount)throw Object.assign(new Error('Célula não encontrada'),{status:404});await event(c,req.params.id,u,'cell_edited',req.params.cellId,{content:content.slice(0,160)});});res.json({ok:true,savedAt:new Date().toISOString()})}catch(e){next(e)}});
app.put('/api/tables/:id/columns/:columnId',async(req,res,next)=>{try{const u=user(req),b=z.object({label:z.string().trim().min(1).max(160)}).parse(req.body);await tx(async c=>{await editable(c,req.params.id,u);await ensureUser(c,u);const r=await c.query('UPDATE table_columns SET label=$1 WHERE table_id=$2 AND id=$3 RETURNING id',[b.label,req.params.id,req.params.columnId]);if(!r.rowCount)throw Object.assign(new Error('Coluna não encontrada'),{status:404});await event(c,req.params.id,u,'column_renamed',req.params.columnId,{label:b.label})});res.json({ok:true})}catch(e){next(e)}});
app.post('/api/tables/:id/structure',async(req,res,next)=>{try{const u=user(req),b=z.object({axis:z.enum(['row','column']),action:z.enum(['add','remove']),position:z.number().int().nonnegative().optional(),id:z.string().uuid().optional()}).parse(req.body);await tx(async c=>{await editable(c,req.params.id,u);await ensureUser(c,u);const table=req.params.id;if(b.axis==='row'&&b.action==='add'){const cr=await c.query('SELECT id FROM table_columns WHERE table_id=$1 ORDER BY position',[table]);const at=b.position??9999;await c.query('UPDATE table_rows SET position=position+1 WHERE table_id=$1 AND position>=$2',[table,at]);const r=await c.query('INSERT INTO table_rows(table_id,position) VALUES($1,$2) RETURNING id',[table,at]);for(const col of cr.rows)await c.query('INSERT INTO cells(table_id,row_id,column_id) VALUES($1,$2,$3)',[table,r.rows[0].id,col.id]);}else if(b.axis==='row'){if(!b.id)throw new Error('Informe a linha');await c.query('DELETE FROM table_rows WHERE table_id=$1 AND id=$2',[table,b.id]);await c.query('UPDATE table_rows SET position=position-1 WHERE table_id=$1 AND position>(SELECT position FROM table_rows WHERE id=$2)',[table,b.id]);}else if(b.action==='add'){const rr=await c.query('SELECT id FROM table_rows WHERE table_id=$1 ORDER BY position',[table]);const at=b.position??9999;await c.query('UPDATE table_columns SET position=position+1 WHERE table_id=$1 AND position>=$2',[table,at]);const col=await c.query('INSERT INTO table_columns(table_id,position,label) VALUES($1,$2,$3) RETURNING id',[table,at,'Nova coluna']);for(const row of rr.rows)await c.query('INSERT INTO cells(table_id,row_id,column_id) VALUES($1,$2,$3)',[table,row.id,col.rows[0].id]);}else{if(!b.id)throw new Error('Informe a coluna');await c.query('DELETE FROM table_columns WHERE table_id=$1 AND id=$2',[table,b.id]);await c.query('UPDATE table_columns SET position=position-1 WHERE table_id=$1 AND position>(SELECT position FROM table_columns WHERE id=$2)',[table,b.id]);}await event(c,table,u,`${b.action}_${b.axis}`,b.id||String(b.position??''),{});});res.json({ok:true})}catch(e){next(e)}});
app.post('/api/tables/:id/state',async(req,res,next)=>{try{const u=user(req),b=z.object({state:z.enum(['draft','finalized']),action:z.enum(['save','finish','continue'])}).parse(req.body);await tx(async c=>{await editable(c,req.params.id,u);await ensureUser(c,u);await c.query('UPDATE tables SET state=$1,updated_at=now() WHERE id=$2',[b.state,req.params.id]);await event(c,req.params.id,u,b.action,'tabela',{state:b.state})});res.json({ok:true})}catch(e){next(e)}});
app.post('/api/tables/:id/archive',async(req,res,next)=>{try{const u=user(req);const r=await pool.query('UPDATE tables SET archived_at=now() WHERE id=$1 AND owner_user_id=$2 RETURNING id',[req.params.id,u.userId]);if(!r.rowCount)return res.status(403).json({error:'Somente o criador pode arquivar.'});await pool.query('INSERT INTO history(table_id,user_id,first_name,last_name,event_type,target) VALUES($1,$2,$3,$4,$5,$6)',[req.params.id,u.userId,u.firstName,u.lastName,'archive','tabela']);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/tables/:id/restore',async(req,res,next)=>{try{const u=user(req);const r=await pool.query('UPDATE tables SET archived_at=NULL WHERE id=$1 AND owner_user_id=$2 RETURNING id',[req.params.id,u.userId]);if(!r.rowCount)return res.status(403).json({error:'Somente o criador pode restaurar.'});await pool.query('INSERT INTO history(table_id,user_id,first_name,last_name,event_type,target) VALUES($1,$2,$3,$4,$5,$6)',[req.params.id,u.userId,u.firstName,u.lastName,'restore','tabela']);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/tables/:id/history',async(req,res,next)=>{try{res.json((await pool.query('SELECT * FROM history WHERE table_id=$1 ORDER BY created_at DESC LIMIT 250',[req.params.id])).rows)}catch(e){next(e)}});
app.get('/api/tables/:id/events',async(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.flushHeaders();const timer=setInterval(()=>res.write(`event: refresh\ndata: ${Date.now()}\n\n`),4000);req.on('close',()=>clearInterval(timer))});
app.post('/api/tables/:id/resize',async(req,res,next)=>{try{const u=user(req),b=z.object({axis:z.enum(['row','column']),id:z.string().uuid(),size:z.number().int().min(36).max(900)}).parse(req.body);await tx(async c=>{await editable(c,req.params.id,u);await ensureUser(c,u);const table=b.axis==='row'?'table_rows':'table_columns',field=b.axis==='row'?'height':'width';await c.query(`UPDATE ${table} SET ${field}=$1 WHERE table_id=$2 AND id=$3`,[b.size,req.params.id,b.id]);await event(c,req.params.id,u,'resize',b.id,{axis:b.axis,size:b.size})});res.json({ok:true})}catch(e){next(e)}});
if(process.env.NODE_ENV==='production'){app.use(express.static(path.resolve('dist')));app.get('*',(_q,res)=>res.sendFile(path.resolve('dist/index.html')))}
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err.message);res.status(err.status|| (err instanceof z.ZodError?400:500)).json({error:err instanceof z.ZodError?'Dados inválidos':err.message||'Erro interno'})});
const port=Number(process.env.PORT||3001);app.listen(port,'0.0.0.0',()=>console.log(`SocioTab API ouvindo em ${port}`));
